# Generated by Django 5.1.2 on 2024-12-17 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_industry_jobalert_job_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobalert',
            name='created_at',
        ),
        migrations.AddField(
            model_name='jobalert',
            name='notified_jobs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
