# Generated by Django 5.1.2 on 2025-03-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_jobpost_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='remaining_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='total_slots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
