# Generated by Django 5.1.2 on 2025-03-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobpost_remaining_slots_jobpost_total_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_hired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
