# Generated by Django 5.1.2 on 2025-03-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_application_is_hired_application_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_hired',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
