# Generated by Django 5.1.2 on 2024-12-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_jobpost_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='employer',
        ),
        migrations.DeleteModel(
            name='JobAlert',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
