# Generated by Django 5.1.2 on 2025-03-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_preferences',
        ),
    ]
